# docker-compose.yml
version: '3.8'

services:
  # Your Node.js backend service
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3000:3000"           # Maps port 3000 on your computer to 3000 in container
    environment:
      - NODE_ENV=development
      - DB_HOST=db            # Points to the database service below
    depends_on:
      - db                    # Ensures database starts first
    volumes:
      - ./backend:/usr/src/app              # For live code updates
      - /usr/src/app/node_modules           # Keeps node_modules in container
    command: npm run dev                    # Runs with nodemon for development

  # MySQL Database service
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"          # Access MySQL from your computer
    environment:
      - MYSQL_DATABASE=tottp_db
      - MYSQL_USER=tottp_user
      - MYSQL_PASSWORD=your_password_here
      - MYSQL_ROOT_PASSWORD=root_password_here
    volumes:
      - mysql_data:/var/lib/mysql                                    # Persists database data
      - ./backend/src/config/init.sql:/docker-entrypoint-initdb.d/init.sql   # Runs on first startup

# Define persistent storage for MySQL data
volumes:
  mysql_data: